language: csharp
install:
- nuget restore opencrypto.sln
- nuget install NUnit.Runners -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Debug opencrypto.sln
- nuget install NUnit.Runners -OutputDirectory testrunner
after_script:
- mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./md5tests/bin/Debug/md5Tests.dll