language: csharp
script:
- xbuild /p:Configuration=Debug opencrypto.sln
before_install:
- sudo apt-get install nunit-console
before_script:
- nuget restore opencrypto.sln
after_script:
- nunit-console *.Tests/bin/Debug/Tests.dll